#!/bin/bash
git init
git clone https://github.com/kumarvirendra186/assignment_repo.git
git status
git add *
git commit -m "added task"
git push https://github.com/kumarvirendra186/assignment_repo.git master
